openapi:"3.0.0"
info:
  title: Composer API
  version: "1.0.1"
paths:
/composers:
  get:
    tags:
      - Composers
    Description: API for returning the list of composers from database.
    summary: returns a list of composers.
    responses:
      "200":
        description: Composer Documents
      "500":
        description: Server Exception
      "501":
        description: 
