openapi: 3.0.0
info:
  title: Person API
  version: 1.0.0
paths:
  /persons:
    get:
      tags:
        - Person
      description: API for returning the list of persons from MongoDB Atlas
      summary: returns a list of persons documents
      responses:
        '200':
          description: Person Documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - Person
      description: API for adding a new person to MongoDB.
      summary: Creates a new person object
      requestBody:
        description: Object information.
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
                - role
                - dependents
                - birthDate
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                role:
                  type: array
                  items:
                    type: object
                    properties:
                      text:
                        type: string
                dependents:
                  type: array
                  items:
                    type: object
                    properties:
                      firstName:
                        type: string
                      lastName:
                        type: string
                birthDate:
                  type: string
      responses:
        '200':
          description: Person Added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
  /persons/{id}:
    get:
      tags:
        - Person
      description: API for returning a single person from MongoDB.
      summary: returns a person document
      parameters:
        - name: id
          in: path
          required: true
          description: The personId requested by the user.
          schema:
            type: string
      responses:
        '200':
          description: Person document in JSON Format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
